import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function cleanDatabase() {
    console.log("Starting DB Cleanup...");

    try {
        // Delete all users EXCEPT the superadmin
        // Prisma's Cascade delete will automatically delete their associated 
        // SellerProfiles, AgentProfiles, Orders, Rooms, FoodItems, Subscriptions, etc.
        const deletedUsers = await prisma.user.deleteMany({
            where: {
                role: {
                    not: "SUPERADMIN"
                }
            }
        });

        console.log(`Successfully deleted ${deletedUsers.count} dummy users and their related data.`);

        // Let's also clear out the coupons just to be safe so the testing is truly clean
        const deletedCoupons = await prisma.coupon.deleteMany();
        console.log(`Cleared ${deletedCoupons.count} coupons.`);

        // Clear out audit logs generated by dummy testing
        await prisma.auditLog.deleteMany();
        console.log("Cleared audit logs.");

        console.log("Database wiped! Only the Superadmin remains.");

    } catch (error) {
        console.error("Error during cleanup:", error);
    } finally {
        await prisma.$disconnect();
    }
}

cleanDatabase();
